from __future__ import annotations

import contextlib
import http.server
import os
import shutil
import socketserver
import subprocess
import threading
from pathlib import Path
from typing import Iterator

import pytest


@pytest.fixture
def script_repo(tmp_path: Path) -> Path:
    root = tmp_path / "repo"
    ios_root = root / "apps/mobile/ios"
    source_root = Path(__file__).resolve().parents[3]
    shutil.copytree(
        source_root / "apps/mobile/ios/Config",
        ios_root / "Config",
        ignore=shutil.ignore_patterns("Deployment.local.xcconfig"),
    )
    shutil.copytree(source_root / "apps/mobile/ios/scripts", ios_root / "scripts")
    subprocess.run(["git", "init"], cwd=root, check=True, capture_output=True, text=True)
    return root


def test_writer_blocks_missing_values(script_repo: Path) -> None:
    result = run_writer(script_repo)

    assert result.returncode == 2
    assert "Missing DEVELOPMENT_TEAM" in result.stderr
    assert not local_config_path(script_repo).exists()


def test_writer_blocks_loopback_backend(script_repo: Path) -> None:
    result = run_writer(
        script_repo,
        env={
            "DEVELOPMENT_TEAM": "ABCDE12345",
            "PRODUCT_BUNDLE_IDENTIFIER": "com.example.personalmythforge",
            "PMF_BACKEND_BASE_URL": "http://127.0.0.1:8080",
        },
    )

    assert result.returncode == 2
    assert "not loopback" in result.stderr
    assert not local_config_path(script_repo).exists()


def test_writer_blocks_unknown_flag(script_repo: Path) -> None:
    result = run_writer(script_repo, "--unknown", "value")

    assert result.returncode == 2
    assert "Unknown option: --unknown" in result.stderr
    assert not local_config_path(script_repo).exists()


def test_writer_refuses_tracked_local_config(script_repo: Path) -> None:
    local_config_path(script_repo).write_text("DEVELOPMENT_TEAM = OLD\n", encoding="utf-8")
    subprocess.run(
        ["git", "add", "apps/mobile/ios/Config/Deployment.local.xcconfig"],
        cwd=script_repo,
        check=True,
        capture_output=True,
        text=True,
    )

    result = run_writer(
        script_repo,
        env={
            "DEVELOPMENT_TEAM": "ABCDE12345",
            "PRODUCT_BUNDLE_IDENTIFIER": "com.example.personalmythforge",
            "PMF_BACKEND_BASE_URL": "http://192.168.1.10:8080",
        },
    )

    assert result.returncode == 1
    assert "must stay untracked" in result.stderr
    assert local_config_path(script_repo).read_text(encoding="utf-8") == "DEVELOPMENT_TEAM = OLD\n"


def test_writer_uses_environment_values(script_repo: Path) -> None:
    result = run_writer(
        script_repo,
        env={
            "DEVELOPMENT_TEAM": "ABCDE12345",
            "PRODUCT_BUNDLE_IDENTIFIER": "com.example.personalmythforge",
            "PMF_BACKEND_BASE_URL": "http://192.168.1.10:8080",
        },
    )

    assert result.returncode == 0
    assert "Deployment.local.xcconfig written." in result.stdout
    assert "Next: make mobile-deploy-preflight" in result.stdout
    assert local_config_path(script_repo).read_text(encoding="utf-8") == (
        "// Generated by write_deploy_local_config.sh. Do not commit.\n"
        "DEVELOPMENT_TEAM = ABCDE12345\n"
        "PRODUCT_BUNDLE_IDENTIFIER = com.example.personalmythforge\n"
        "PMF_BACKEND_BASE_URL = http://192.168.1.10:8080\n"
        "PMF_FINAL_LAUNCH_MODE = local\n"
    )


def test_writer_uses_base_bundle_identifier_when_not_provided(script_repo: Path) -> None:
    result = run_writer(
        script_repo,
        env={
            "DEVELOPMENT_TEAM": "ABCDE12345",
            "PMF_BACKEND_BASE_URL": "http://192.168.1.10:8080",
        },
    )

    assert result.returncode == 0
    assert "Deployment.local.xcconfig written." in result.stdout
    assert local_config_path(script_repo).read_text(encoding="utf-8") == (
        "// Generated by write_deploy_local_config.sh. Do not commit.\n"
        "DEVELOPMENT_TEAM = ABCDE12345\n"
        "PRODUCT_BUNDLE_IDENTIFIER = com.personalmythforge.app\n"
        "PMF_BACKEND_BASE_URL = http://192.168.1.10:8080\n"
        "PMF_FINAL_LAUNCH_MODE = local\n"
    )


def test_writer_resolves_auto_backend_url_from_override(script_repo: Path) -> None:
    result = run_writer(
        script_repo,
        env={
            "DEVELOPMENT_TEAM": "ABCDE12345",
            "PRODUCT_BUNDLE_IDENTIFIER": "com.example.personalmythforge",
            "PMF_BACKEND_BASE_URL": "auto",
            "PMF_BACKEND_AUTO_HOST": "10.0.0.24",
            "PMF_BACKEND_PORT": "9090",
        },
    )

    assert result.returncode == 0
    assert "Auto backend URL: http://10.0.0.24:9090" in result.stdout
    assert "Backend: http://10.0.0.24:9090" in result.stdout
    assert "PMF_BACKEND_BASE_URL = http://10.0.0.24:9090" in local_config_path(
        script_repo
    ).read_text(encoding="utf-8")


def test_writer_rejects_auto_loopback_backend_host(script_repo: Path) -> None:
    result = run_writer(
        script_repo,
        env={
            "DEVELOPMENT_TEAM": "ABCDE12345",
            "PRODUCT_BUNDLE_IDENTIFIER": "com.example.personalmythforge",
            "PMF_BACKEND_BASE_URL": "auto",
            "PMF_BACKEND_AUTO_HOST": "127.0.0.1",
        },
    )

    assert result.returncode == 2
    assert "not loopback" in result.stderr
    assert not local_config_path(script_repo).exists()


def test_writer_blocks_invalid_final_launch_mode(script_repo: Path) -> None:
    result = run_writer(
        script_repo,
        env={
            "DEVELOPMENT_TEAM": "ABCDE12345",
            "PRODUCT_BUNDLE_IDENTIFIER": "com.example.personalmythforge",
            "PMF_BACKEND_BASE_URL": "http://192.168.1.10:8080",
            "PMF_FINAL_LAUNCH_MODE": "live",
        },
    )

    assert result.returncode == 2
    assert "PMF_FINAL_LAUNCH_MODE must be local or configured." in result.stderr
    assert not local_config_path(script_repo).exists()


def test_writer_flags_override_environment(script_repo: Path) -> None:
    result = run_writer(
        script_repo,
        "--team",
        "FGHIJ67890",
        "--bundle-id",
        "com.example.flags",
        "--backend-url",
        "http://192.168.1.11:8080",
        "--final-launch-mode",
        "configured",
        env={
            "DEVELOPMENT_TEAM": "ABCDE12345",
            "PRODUCT_BUNDLE_IDENTIFIER": "com.example.env",
            "PMF_BACKEND_BASE_URL": "http://192.168.1.10:8080",
            "PMF_FINAL_LAUNCH_MODE": "local",
        },
    )

    assert result.returncode == 0
    assert "Bundle: com.example.flags" in result.stdout
    assert "Backend: http://192.168.1.11:8080" in result.stdout
    written = local_config_path(script_repo).read_text(encoding="utf-8")
    assert "FGHIJ67890" in written
    assert "com.example.flags" in written
    assert "192.168.1.11" in written
    assert "PMF_FINAL_LAUNCH_MODE = configured" in written


def test_writer_output_passes_existing_deploy_preflight(script_repo: Path) -> None:
    with health_server('{"status":"ok"}') as backend_url:
        writer_result = run_writer(
            script_repo,
            "--team",
            "ABCDE12345",
            "--bundle-id",
            "com.example.personalmythforge",
            "--backend-url",
            backend_url,
        )
        preflight_result = run_preflight(script_repo)

    assert writer_result.returncode == 0
    assert preflight_result.returncode == 0
    assert "Backend health: ok" in preflight_result.stdout


def run_writer(
    root: Path,
    *args: str,
    env: dict[str, str] | None = None,
) -> subprocess.CompletedProcess[str]:
    process_env = os.environ.copy()
    if env is not None:
        process_env.update(env)
    return subprocess.run(
        ["sh", "apps/mobile/ios/scripts/write_deploy_local_config.sh", *args],
        cwd=root,
        check=False,
        capture_output=True,
        text=True,
        env=process_env,
    )


def run_preflight(root: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["apps/mobile/ios/scripts/deploy_preflight.sh"],
        cwd=root,
        check=False,
        capture_output=True,
        text=True,
    )


def local_config_path(root: Path) -> Path:
    return root / "apps/mobile/ios/Config/Deployment.local.xcconfig"


@contextlib.contextmanager
def health_server(body: str) -> Iterator[str]:
    class Handler(http.server.BaseHTTPRequestHandler):
        def do_GET(self) -> None:  # noqa: N802
            if self.path != "/health":
                self.send_response(404)
                self.end_headers()
                return
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(body.encode("utf-8"))

        def log_message(self, format: str, *args: object) -> None:
            return

    with socketserver.TCPServer(("127.0.0.1", 0), Handler) as server:
        port = server.server_address[1]
        thread = threading.Thread(target=server.serve_forever)
        thread.start()
        try:
            yield f"http://0.0.0.0:{port}"
        finally:
            server.shutdown()
            thread.join(timeout=5)
