from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import pytest
from dotenv import dotenv_values

from myth_forge_api.config import load_settings


EXPECTED_ENV_WITH_OPTIONAL = """# Generated by write_backend_env.sh. Do not commit.
MYTH_FORGE_ENV=local
MYTH_FORGE_API_HOST=127.0.0.1
MYTH_FORGE_API_PORT=8080
THREE_D_PROVIDER=meshy
MESHY_API_BASE_URL=https://api.meshy.ai
MESHY_POLL_INTERVAL_SECONDS=5
MESHY_MAX_WAIT_SECONDS=600
MESHY_API_KEY=meshy-secret-test
NPC_PROVIDER=openai
OPENAI_NPC_MODEL=gpt-4.1-mini
OPENAI_API_BASE_URL=
OPENAI_API_KEY=sk-openai-test
PRINT_PROVIDER=local
TREATSTOCK_API_BASE_URL=https://www.treatstock.com
TREATSTOCK_API_KEY=treatstock-optional
SCULPTEO_API_KEY=
CAPTURE_STORAGE_DIR=
MYTH_SESSION_STORAGE_DIR=
"""


@pytest.fixture
def script_repo(tmp_path: Path) -> Path:
    root = tmp_path / "repo"
    backend_root = root / "services/backend"
    scripts_root = backend_root / "scripts"
    source_root = Path(__file__).resolve().parents[3]
    source_scripts = source_root / "services/backend/scripts"
    if source_scripts.exists():
        shutil.copytree(source_scripts, scripts_root)
    else:
        scripts_root.mkdir(parents=True)
    subprocess.run(["git", "init"], cwd=root, check=True, capture_output=True, text=True)
    return root


def test_writer_blocks_missing_meshy_key(script_repo: Path) -> None:
    result = run_writer(script_repo, env={"OPENAI_API_KEY": "sk-openai-test"})

    assert result.returncode == 2
    assert "Missing MESHY_API_KEY" in result.stderr
    assert not backend_env_path(script_repo).exists()
    assert "sk-openai-test" not in result.stderr


def test_writer_blocks_missing_openai_key(script_repo: Path) -> None:
    result = run_writer(script_repo, env={"MESHY_API_KEY": "meshy-secret-test"})

    assert result.returncode == 2
    assert "Missing OPENAI_API_KEY" in result.stderr
    assert not backend_env_path(script_repo).exists()
    assert "meshy-secret-test" not in result.stderr


def test_writer_blocks_unknown_flag(script_repo: Path) -> None:
    result = run_writer(script_repo, "--unknown", "value")

    assert result.returncode == 2
    assert "Unknown option: --unknown" in result.stderr
    assert not backend_env_path(script_repo).exists()


def test_writer_refuses_tracked_backend_env(script_repo: Path) -> None:
    backend_env_path(script_repo).write_text("MESHY_API_KEY=old\n", encoding="utf-8")
    subprocess.run(
        ["git", "add", "services/backend/.env"],
        cwd=script_repo,
        check=True,
        capture_output=True,
        text=True,
    )

    result = run_writer(
        script_repo,
        env={"MESHY_API_KEY": "meshy-secret-test", "OPENAI_API_KEY": "sk-openai-test"},
    )

    assert result.returncode == 1
    assert "services/backend/.env must stay untracked" in result.stderr
    assert backend_env_path(script_repo).read_text(encoding="utf-8") == "MESHY_API_KEY=old\n"


def test_writer_uses_environment_values_and_redacts_output(script_repo: Path) -> None:
    result = run_writer(
        script_repo,
        env={
            "MESHY_API_KEY": "meshy-secret-test",
            "OPENAI_API_KEY": "sk-openai-test",
            "TREATSTOCK_API_KEY": "treatstock-optional",
        },
    )

    assert result.returncode == 0
    assert "services/backend/.env written." in result.stdout
    assert "MESHY_API_KEY: configured (redacted)" in result.stdout
    assert "OPENAI_API_KEY: configured (redacted)" in result.stdout
    assert "meshy-secret-test" not in result.stdout + result.stderr
    assert "sk-openai-test" not in result.stdout + result.stderr
    assert "treatstock-optional" not in result.stdout + result.stderr
    assert backend_env_path(script_repo).read_text(encoding="utf-8") == EXPECTED_ENV_WITH_OPTIONAL


def test_writer_flags_override_environment(script_repo: Path) -> None:
    result = run_writer(
        script_repo,
        "--meshy-key",
        "meshy-from-flags",
        "--openai-key",
        "sk-openai-flags",
        "--openai-base-url",
        "https://api.openai.test/v1",
        "--print-provider",
        "treatstock",
        "--treatstock-key",
        "treatstock-from-flags",
        "--treatstock-base-url",
        "https://treatstock.test",
        env={"MESHY_API_KEY": "meshy-from-env", "OPENAI_API_KEY": "sk-openai-env"},
    )

    assert result.returncode == 0
    written = backend_env_path(script_repo).read_text(encoding="utf-8")
    assert "MESHY_API_KEY=meshy-from-flags" in written
    assert "OPENAI_API_KEY=sk-openai-flags" in written
    assert "OPENAI_API_BASE_URL=https://api.openai.test/v1" in written
    assert "PRINT_PROVIDER=treatstock" in written
    assert "TREATSTOCK_API_KEY=treatstock-from-flags" in written
    assert "TREATSTOCK_API_BASE_URL=https://treatstock.test" in written
    assert "meshy-from-env" not in written
    assert "sk-openai-env" not in written


def test_writer_requires_treatstock_key_when_treatstock_is_selected(script_repo: Path) -> None:
    result = run_writer(
        script_repo,
        env={
            "MESHY_API_KEY": "meshy-secret-test",
            "OPENAI_API_KEY": "sk-openai-test",
            "PRINT_PROVIDER": "treatstock",
        },
    )

    assert result.returncode == 2
    assert "TREATSTOCK_API_KEY is required when PRINT_PROVIDER=treatstock" in result.stderr
    assert not backend_env_path(script_repo).exists()


def test_writer_blocks_multiline_values(script_repo: Path) -> None:
    result = run_writer(
        script_repo,
        env={
            "MESHY_API_KEY": "meshy-secret-test\nextra",
            "OPENAI_API_KEY": "sk-openai-test",
        },
    )

    assert result.returncode == 2
    assert "Backend env values must be single-line strings." in result.stderr
    assert not backend_env_path(script_repo).exists()


def test_writer_output_can_be_loaded_as_settings(
    script_repo: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    result = run_writer(
        script_repo,
        "--meshy-key",
        "meshy-from-flags",
        "--openai-key",
        "sk-openai-flags",
    )

    assert result.returncode == 0
    monkeypatch.chdir(script_repo / "services/backend")
    raw_values = dotenv_values(".env")
    settings = load_settings(
        env={key: value or "" for key, value in raw_values.items()}
    )
    assert settings.three_d_provider == "meshy"
    assert settings.meshy_api_key == "meshy-from-flags"
    assert settings.npc_provider == "openai"
    assert settings.openai_api_key == "sk-openai-flags"
    assert settings.print_provider == "local"


def run_writer(
    root: Path,
    *args: str,
    env: dict[str, str] | None = None,
) -> subprocess.CompletedProcess[str]:
    process_env = {
        "PATH": os.environ.get("PATH", ""),
        "HOME": os.environ.get("HOME", ""),
    }
    if env is not None:
        process_env.update(env)
    return subprocess.run(
        ["sh", "services/backend/scripts/write_backend_env.sh", *args],
        cwd=root,
        check=False,
        capture_output=True,
        text=True,
        env=process_env,
    )


def backend_env_path(root: Path) -> Path:
    return root / "services/backend/.env"
