#!/usr/bin/env sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
IOS_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
CONFIG_DIR="$IOS_ROOT/Config"
LOCAL_CONFIG="$CONFIG_DIR/Deployment.local.xcconfig"

usage() {
  cat <<'EOF'
Usage: write_deploy_local_config.sh [--team TEAM_ID] [--bundle-id BUNDLE_ID] [--backend-url URL] [--final-launch-mode MODE]

Values default to DEVELOPMENT_TEAM, PRODUCT_BUNDLE_IDENTIFIER, PMF_BACKEND_BASE_URL,
and PMF_FINAL_LAUNCH_MODE. Use PMF_BACKEND_BASE_URL=auto to derive the backend
URL from this Mac's LAN address.
EOF
}

has_line_break() {
  case "$1" in
    *"
"*|*"
"*) return 0 ;;
    *) return 1 ;;
  esac
}

resolve_auto_backend_url() {
  port="${PMF_BACKEND_PORT:-8080}"
  case "$port" in
    ""|*[!0-9]*) return 1 ;;
  esac
  if [ -n "${PMF_BACKEND_AUTO_HOST:-}" ]; then
    printf 'http://%s:%s' "$PMF_BACKEND_AUTO_HOST" "$port"
    return 0
  fi
  if ! command -v python3 >/dev/null 2>&1; then
    return 1
  fi
  PMF_BACKEND_PORT="$port" python3 - <<'PY'
import os
import socket
import sys

port = os.environ.get("PMF_BACKEND_PORT", "8080")
hosts = []
for target in [("8.8.8.8", 80), ("1.1.1.1", 80), ("224.0.0.1", 1)]:
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        sock.connect(target)
        host = sock.getsockname()[0]
        if host and not host.startswith("127.") and host != "0.0.0.0":
            hosts.append(host)
    except OSError:
        pass
    finally:
        sock.close()
try:
    for host in socket.gethostbyname_ex(socket.gethostname())[2]:
        if host and not host.startswith("127.") and host != "0.0.0.0":
            hosts.append(host)
except OSError:
    pass
for host in hosts:
    print(f"http://{host}:{port}")
    sys.exit(0)
sys.exit(1)
PY
}

team="${DEVELOPMENT_TEAM:-}"
bundle_id="${PRODUCT_BUNDLE_IDENTIFIER:-}"
backend_url="${PMF_BACKEND_BASE_URL:-}"
final_launch_mode="${PMF_FINAL_LAUNCH_MODE:-local}"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --team)
      if [ "$#" -lt 2 ]; then
        printf '%s\n' "Missing value for --team." >&2
        exit 2
      fi
      team="$2"
      shift 2
      ;;
    --bundle-id)
      if [ "$#" -lt 2 ]; then
        printf '%s\n' "Missing value for --bundle-id." >&2
        exit 2
      fi
      bundle_id="$2"
      shift 2
      ;;
    --backend-url)
      if [ "$#" -lt 2 ]; then
        printf '%s\n' "Missing value for --backend-url." >&2
        exit 2
      fi
      backend_url="$2"
      shift 2
      ;;
    --final-launch-mode)
      if [ "$#" -lt 2 ]; then
        printf '%s\n' "Missing value for --final-launch-mode." >&2
        exit 2
      fi
      final_launch_mode="$2"
      shift 2
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      printf '%s\n' "Unknown option: $1" >&2
      exit 2
      ;;
  esac
done

missing=0
if [ "$backend_url" = "auto" ]; then
  resolved_backend_url=$(resolve_auto_backend_url || true)
  if [ -z "$resolved_backend_url" ]; then
    printf '%s\n' "Could not auto-detect a non-loopback backend host." >&2
    missing=1
  else
    backend_url="$resolved_backend_url"
    printf '%s\n' "Auto backend URL: $backend_url"
  fi
fi
if [ -z "$team" ]; then
  printf '%s\n' "Missing DEVELOPMENT_TEAM. Set env var or pass --team." >&2
  missing=1
fi
if [ -z "$bundle_id" ]; then
  printf '%s\n' "Missing PRODUCT_BUNDLE_IDENTIFIER. Set env var or pass --bundle-id." >&2
  missing=1
fi
if [ -z "$backend_url" ]; then
  printf '%s\n' "Missing PMF_BACKEND_BASE_URL. Set env var or pass --backend-url." >&2
  missing=1
fi

for value in "$team" "$bundle_id" "$backend_url" "$final_launch_mode"; do
  if has_line_break "$value"; then
    printf '%s\n' "Deployment values must be single-line strings." >&2
    missing=1
  fi
done

case "$backend_url" in
  http://127.0.0.1*|http://localhost*|https://127.0.0.1*|https://localhost*)
    printf '%s\n' "PMF_BACKEND_BASE_URL must be reachable from iPhone, not loopback." >&2
    missing=1
    ;;
esac

final_launch_mode=$(printf '%s' "$final_launch_mode" | tr '[:upper:]' '[:lower:]')
case "$final_launch_mode" in
  local|configured) ;;
  *)
    printf '%s\n' "PMF_FINAL_LAUNCH_MODE must be local or configured." >&2
    missing=1
    ;;
esac

if [ "$missing" -ne 0 ]; then
  exit 2
fi

REPOSITORY_ROOT=$(git -C "$IOS_ROOT" rev-parse --show-toplevel 2>/dev/null || true)
if [ -n "$REPOSITORY_ROOT" ] &&
  git -C "$REPOSITORY_ROOT" ls-files --error-unmatch "apps/mobile/ios/Config/Deployment.local.xcconfig" >/dev/null 2>&1; then
  printf '%s\n' "Deployment.local.xcconfig must stay untracked." >&2
  exit 1
fi

tmp_file="$LOCAL_CONFIG.tmp.$$"
trap 'rm -f "$tmp_file"' EXIT HUP INT TERM

{
  printf '%s\n' "// Generated by write_deploy_local_config.sh. Do not commit."
  printf '%s\n' "DEVELOPMENT_TEAM = $team"
  printf '%s\n' "PRODUCT_BUNDLE_IDENTIFIER = $bundle_id"
  printf '%s\n' "PMF_BACKEND_BASE_URL = $backend_url"
  printf '%s\n' "PMF_FINAL_LAUNCH_MODE = $final_launch_mode"
} >"$tmp_file"
mv "$tmp_file" "$LOCAL_CONFIG"
if command -v chmod >/dev/null 2>&1; then
  chmod 600 "$LOCAL_CONFIG"
fi
trap - EXIT HUP INT TERM

printf '%s\n' "Deployment.local.xcconfig written."
printf '%s\n' "Bundle: $bundle_id"
printf '%s\n' "Backend: $backend_url"
printf '%s\n' "Next: make mobile-deploy-preflight"
