#!/usr/bin/env sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
BACKEND_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
ENV_FILE="$BACKEND_ROOT/.env"

usage() {
  cat <<'EOF'
Usage: write_backend_env.sh [options]

Required values default to MESHY_API_KEY and OPENAI_API_KEY.

Options:
  --meshy-key VALUE
  --openai-key VALUE
  --openai-base-url VALUE
  --treatstock-key VALUE
  --sculpteo-key VALUE
  --capture-storage-dir VALUE
  --myth-session-storage-dir VALUE
  --help
EOF
}

has_line_break() {
  newline='
'
  case "$1" in
    *"$newline"*) return 0 ;;
    *) return 1 ;;
  esac
}

require_arg() {
  if [ "$#" -lt 2 ]; then
    printf '%s\n' "Missing value for $1." >&2
    exit 2
  fi
}

meshy_key="${MESHY_API_KEY:-}"
openai_key="${OPENAI_API_KEY:-}"
openai_base_url="${OPENAI_API_BASE_URL:-}"
treatstock_key="${TREATSTOCK_API_KEY:-}"
sculpteo_key="${SCULPTEO_API_KEY:-}"
capture_storage_dir="${CAPTURE_STORAGE_DIR:-}"
myth_session_storage_dir="${MYTH_SESSION_STORAGE_DIR:-}"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --meshy-key)
      require_arg "$1" "$@"
      meshy_key="$2"
      shift 2
      ;;
    --openai-key)
      require_arg "$1" "$@"
      openai_key="$2"
      shift 2
      ;;
    --openai-base-url)
      require_arg "$1" "$@"
      openai_base_url="$2"
      shift 2
      ;;
    --treatstock-key)
      require_arg "$1" "$@"
      treatstock_key="$2"
      shift 2
      ;;
    --sculpteo-key)
      require_arg "$1" "$@"
      sculpteo_key="$2"
      shift 2
      ;;
    --capture-storage-dir)
      require_arg "$1" "$@"
      capture_storage_dir="$2"
      shift 2
      ;;
    --myth-session-storage-dir)
      require_arg "$1" "$@"
      myth_session_storage_dir="$2"
      shift 2
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      printf '%s\n' "Unknown option: $1" >&2
      exit 2
      ;;
  esac
done

missing=0
if [ -z "$meshy_key" ]; then
  printf '%s\n' "Missing MESHY_API_KEY. Set env var or pass --meshy-key." >&2
  missing=1
fi
if [ -z "$openai_key" ]; then
  printf '%s\n' "Missing OPENAI_API_KEY. Set env var or pass --openai-key." >&2
  missing=1
fi

for value in \
  "$meshy_key" \
  "$openai_key" \
  "$openai_base_url" \
  "$treatstock_key" \
  "$sculpteo_key" \
  "$capture_storage_dir" \
  "$myth_session_storage_dir"; do
  if has_line_break "$value"; then
    printf '%s\n' "Backend env values must be single-line strings." >&2
    missing=1
  fi
done

if [ "$missing" -ne 0 ]; then
  exit 2
fi

REPOSITORY_ROOT=$(git -C "$BACKEND_ROOT" rev-parse --show-toplevel 2>/dev/null || true)
if [ -n "$REPOSITORY_ROOT" ] &&
  git -C "$REPOSITORY_ROOT" ls-files --error-unmatch "services/backend/.env" >/dev/null 2>&1; then
  printf '%s\n' "services/backend/.env must stay untracked." >&2
  exit 1
fi

tmp_file="$ENV_FILE.tmp.$$"
trap 'rm -f "$tmp_file"' EXIT HUP INT TERM

{
  printf '%s\n' "# Generated by write_backend_env.sh. Do not commit."
  printf '%s\n' "MYTH_FORGE_ENV=local"
  printf '%s\n' "MYTH_FORGE_API_HOST=127.0.0.1"
  printf '%s\n' "MYTH_FORGE_API_PORT=8080"
  printf '%s\n' "THREE_D_PROVIDER=meshy"
  printf '%s\n' "MESHY_API_BASE_URL=https://api.meshy.ai"
  printf '%s\n' "MESHY_POLL_INTERVAL_SECONDS=5"
  printf '%s\n' "MESHY_MAX_WAIT_SECONDS=600"
  printf '%s\n' "MESHY_API_KEY=$meshy_key"
  printf '%s\n' "NPC_PROVIDER=openai"
  printf '%s\n' "OPENAI_NPC_MODEL=gpt-4.1-mini"
  printf '%s\n' "OPENAI_API_BASE_URL=$openai_base_url"
  printf '%s\n' "OPENAI_API_KEY=$openai_key"
  printf '%s\n' "PRINT_PROVIDER=local"
  printf '%s\n' "TREATSTOCK_API_KEY=$treatstock_key"
  printf '%s\n' "SCULPTEO_API_KEY=$sculpteo_key"
  printf '%s\n' "CAPTURE_STORAGE_DIR=$capture_storage_dir"
  printf '%s\n' "MYTH_SESSION_STORAGE_DIR=$myth_session_storage_dir"
} >"$tmp_file"
mv "$tmp_file" "$ENV_FILE"
if command -v chmod >/dev/null 2>&1; then
  chmod 600 "$ENV_FILE"
fi
trap - EXIT HUP INT TERM

printf '%s\n' "services/backend/.env written."
printf '%s\n' "THREE_D_PROVIDER: meshy"
printf '%s\n' "MESHY_API_KEY: configured (redacted)"
printf '%s\n' "NPC_PROVIDER: openai"
printf '%s\n' "OPENAI_API_KEY: configured (redacted)"
printf '%s\n' "PRINT_PROVIDER: local"
printf '%s\n' "Next: cd services/backend && uv run python -m myth_forge_api.cli provider-handoff --require-core-real"
